server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: consumer-kafka-ms
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:5432/${BD_NAME}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}